version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    environment:
      - NODE_ENV=production
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:5173',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    container_name: frontend-app
    restart: unless-stopped
